use_frameworks!
platform :ios, '10.1'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

#  pod 'LHXKit/AppBuilder', git: 'https://github.com/caoer/LHXKit'
#  pod 'LHXKit/Network', git: 'https://github.com/caoer/LHXKit'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end

target '${POD_NAME}_PatcherGenerator' do
  pod 'AceFileGenerator', git: 'https://github.com/caoer/AceFileGenerator'
end

post_install do |installer|
  `git clone https://github.com/caoer/AceFileGenerator-template ../AceFileGenerator-template`
end