source 'https://github.com/caoer/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.1'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  pod 'LHXHowl'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end

target '${POD_NAME}_PatcherGenerator' do
  #TODO: add necesary dependency here
  pod 'AceFileGenerator', git: 'https://github.com/caoer/AceFileGenerator'
end

post_install do |installer|
  if File.exist?('../AceFileGenerator-template')
    `cd ../AceFileGenerator-template; git pull;`
  else 
    `git submodule add https://github.com/caoer/AceFileGenerator-template ../AceFileGenerator-template`
  end

  if File.exist?('../AceFileAutoFix')
    `cd ../AceFileAutoFix`
  else
    `git submodule add https://github.com/caoer/AceFileAutoFix ../AceFileAutoFix`
  end

  if File.exist?('../ace-apps')
  else
    `git clone https://github.com/caoer/ace-apps-template ../ace-apps`
    `cd ../ace-apps; npm install; rm -rf .git`
  end
end
